export interface PeptideGuideEntry {
  name: string;
  category: string;
  vialSize: string;
  reconstitute: string;
  dose: string;
  frequency: string;
  cycle: string;
  note: string;
}

export const peptideCategories = [
  "All",
  "Weight Loss",
  "Fat Loss / Muscle",
  "Muscle Growth",
  "Recovery & Repair",
  "Cognitive",
  "Longevity & Anti-Aging",
  "Immune & Gut",
  "Sexual Health",
  "Skin & UV Protection",
] as const;

export type PeptideCategory = (typeof peptideCategories)[number];

export const peptideGuideData: PeptideGuideEntry[] = [
  {
    name: "Retatrutide",
    category: "Weight Loss",
    vialSize: "10 mg",
    reconstitute: "2 mL",
    dose: "500 mcg – 12 mg",
    frequency: "Microdose EOD 500 mcg (titrate up)",
    cycle: "12–48 weeks",
    note: "Triple agonist; microdose for fewer side effects",
  },
  {
    name: "Semaglutide",
    category: "Weight Loss",
    vialSize: "5 mg",
    reconstitute: "2 mL",
    dose: "0.25–2.5 mg",
    frequency: "Weekly",
    cycle: "16+ weeks",
    note: "Long-acting GLP-1",
  },
  {
    name: "Tirzepatide",
    category: "Weight Loss",
    vialSize: "10 mg",
    reconstitute: "2 mL",
    dose: "500 mcg – 15 mg",
    frequency: "Microdose EOD 500 mcg (titrate up)",
    cycle: "16+ weeks",
    note: "Dual GIP/GLP-1 agonist",
  },
  {
    name: "AOD-9604",
    category: "Weight Loss",
    vialSize: "5 mg",
    reconstitute: "2 mL BAC + 0.5 mL acetic acid",
    dose: "300 mcg",
    frequency: "5 days on / 2 days off",
    cycle: "8 weeks",
    note: "HGH fragment that promotes fat burning",
  },
  {
    name: "Pramlintide",
    category: "Weight Loss",
    vialSize: "5 mg",
    reconstitute: "2 mL",
    dose: "30–60 mcg",
    frequency: "3× daily (pre-meal)",
    cycle: "12–16 weeks",
    note: "Amylin analog that suppresses appetite",
  },
  {
    name: "Liraglutide",
    category: "Weight Loss",
    vialSize: "18 mg pen",
    reconstitute: "N/A",
    dose: "0.6–3.0 mg",
    frequency: "Daily",
    cycle: "16+ weeks",
    note: "GLP-1 agonist for weight loss (pre-filled pen)",
  },
  {
    name: "Adipotide",
    category: "Weight Loss",
    vialSize: "5 mg",
    reconstitute: "2 mL",
    dose: "0.5–1 mg",
    frequency: "Daily",
    cycle: "4 weeks",
    note: "Experimental; targets fat cell blood supply",
  },
  {
    name: "5-Amino 1MQ",
    category: "Weight Loss",
    vialSize: "5–25 mg",
    reconstitute: "3 mL",
    dose: "250 mcg – 5 mg (Sub) / 50 mg (Oral)",
    frequency: "Daily",
    cycle: "8 weeks",
    note: "Weight and fat loss, mitochondria function",
  },
  {
    name: "Cagrilintide",
    category: "Weight Loss",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "0.25–0.5 mg",
    frequency: "2–3×/week",
    cycle: "8–12 weeks",
    note: "Amylin analog; suppresses appetite",
  },
  {
    name: "CJC-1295 DAC",
    category: "Fat Loss / Muscle",
    vialSize: "2 mg",
    reconstitute: "2 mL",
    dose: "1–2 mg",
    frequency: "Weekly",
    cycle: "8–12 weeks",
    note: "Long-acting GHRH analog for steady GH",
  },
  {
    name: "CJC-1295 No DAC",
    category: "Fat Loss / Muscle",
    vialSize: "5 mg",
    reconstitute: "3 mL",
    dose: "100–250 mcg",
    frequency: "5 days on / 2 days off",
    cycle: "8–12 weeks",
    note: "Short-acting GHRH analog for GH pulses",
  },
  {
    name: "Ipamorelin",
    category: "Fat Loss / Muscle",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "300 mcg",
    frequency: "5 days on / 2 off (night, 2h fasted)",
    cycle: "8–12 weeks",
    note: "GH secretagogue with minimal side effects",
  },
  {
    name: "Tesamorelin",
    category: "Fat Loss / Muscle",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "500 mcg – 2 mg",
    frequency: "5 days on / 2 days off",
    cycle: "8–12 weeks",
    note: "Reduces visceral fat, improves metabolism",
  },
  {
    name: "SLU-PP-332",
    category: "Fat Loss / Muscle",
    vialSize: "Capsules",
    reconstitute: "N/A",
    dose: "250 mcg – 1.5 mg",
    frequency: "5 days on / 2 days off",
    cycle: "8–12 weeks",
    note: "Reduces fat, increases endurance",
  },
  {
    name: "GHRP-6",
    category: "Muscle Growth",
    vialSize: "5 mg",
    reconstitute: "3 mL",
    dose: "100–200 mcg",
    frequency: "1–2× daily",
    cycle: "8–12 weeks",
    note: "Stimulates GH release and appetite",
  },
  {
    name: "Follistatin-344",
    category: "Muscle Growth",
    vialSize: "1 mg",
    reconstitute: "1 mL",
    dose: "50 mcg",
    frequency: "2–3×/week (IM)",
    cycle: "8 weeks",
    note: "Inhibits myostatin (IM)",
  },
  {
    name: "GHRP-2",
    category: "Muscle Growth",
    vialSize: "5 mg",
    reconstitute: "3 mL",
    dose: "100–200 mcg",
    frequency: "1–2× daily",
    cycle: "8–12 weeks",
    note: "GH release, less hunger than GHRP-6",
  },
  {
    name: "Hexarelin",
    category: "Muscle Growth",
    vialSize: "2 mg",
    reconstitute: "1 mL",
    dose: "100 mcg",
    frequency: "1–2× daily",
    cycle: "4 weeks on / 4 off",
    note: "Strong GH release, desensitizes quickly (subQ)",
  },
  {
    name: "IGF-1 LR3",
    category: "Muscle Growth",
    vialSize: "1 mg",
    reconstitute: "1 mL",
    dose: "20–50 mcg",
    frequency: "Daily",
    cycle: "3–4 weeks",
    note: "Anabolic; promotes muscle growth (subQ/IM)",
  },
  {
    name: "MGF (Mechano Growth Factor)",
    category: "Muscle Growth",
    vialSize: "2 mg",
    reconstitute: "1 mL",
    dose: "200–400 mcg",
    frequency: "2×/week",
    cycle: "4–6 weeks",
    note: "Stimulates muscle repair post-exercise (subQ/IM)",
  },
  {
    name: "PEG-MGF",
    category: "Muscle Growth",
    vialSize: "2 mg",
    reconstitute: "1 mL",
    dose: "200–400 mcg",
    frequency: "2×/week",
    cycle: "4–6 weeks",
    note: "Supports muscle repair post-workout (subQ/IM)",
  },
  {
    name: "BPC-157",
    category: "Recovery & Repair",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "250–500 mcg",
    frequency: "Daily",
    cycle: "As needed",
    note: "Accelerates tissue healing",
  },
  {
    name: "Cartalax",
    category: "Recovery & Repair",
    vialSize: "20 mg",
    reconstitute: "3 mL",
    dose: "100–300 mcg",
    frequency: "Daily",
    cycle: "20–40 days",
    note: "Joint health, repair and regeneration",
  },
  {
    name: "TB-500",
    category: "Recovery & Repair",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "1–2 mg",
    frequency: "Every 2 days",
    cycle: "4–6 weeks",
    note: "Regenerates tissue, reduces inflammation",
  },
  {
    name: "Thymosin Beta-4",
    category: "Recovery & Repair",
    vialSize: "10 mg",
    reconstitute: "2 mL",
    dose: "2–5 mg",
    frequency: "Weekly",
    cycle: "4–6 weeks",
    note: "Promotes regeneration",
  },
  {
    name: "ARA-290",
    category: "Recovery & Repair",
    vialSize: "5 mg",
    reconstitute: "2 mL",
    dose: "4 mg",
    frequency: "Daily",
    cycle: "4–12 weeks",
    note: "Improves nerve repair, reduces pain",
  },
  {
    name: "Cerebrolysin",
    category: "Cognitive",
    vialSize: "10 mL",
    reconstitute: "N/A",
    dose: "1–5 mL",
    frequency: "Daily",
    cycle: "4–6 weeks",
    note: "Neurotrophic blend for brain recovery",
  },
  {
    name: "Dihexa",
    category: "Cognitive",
    vialSize: "10 mg",
    reconstitute: "2 mL",
    dose: "10–20 mg",
    frequency: "Daily",
    cycle: "4–8 weeks",
    note: "Potent nootropic; enhances cognition",
  },
  {
    name: "Pinealon",
    category: "Cognitive",
    vialSize: "20 mg",
    reconstitute: "3 mL",
    dose: "2 mg",
    frequency: "Daily",
    cycle: "10–20 days",
    note: "Neuroprotective peptide",
  },
  {
    name: "Selank",
    category: "Cognitive",
    vialSize: "20 mg",
    reconstitute: "3 mL",
    dose: "500–1000 mcg",
    frequency: "Daily",
    cycle: "4–6 weeks",
    note: "Anxiolytic and nootropic",
  },
  {
    name: "Semax",
    category: "Cognitive",
    vialSize: "20 mg",
    reconstitute: "3 mL",
    dose: "500–1000 mcg",
    frequency: "Daily",
    cycle: "4–6 weeks",
    note: "Enhances memory and focus",
  },
  {
    name: "Epithalon",
    category: "Longevity & Anti-Aging",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "1–5 mg",
    frequency: "Daily",
    cycle: "20 consecutive days",
    note: "Telomerase activator, used in cycles",
  },
  {
    name: "FOXO4-DRI",
    category: "Longevity & Anti-Aging",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "2–10 mg",
    frequency: "Bi-weekly",
    cycle: "4 weeks",
    note: "Experimental senolytic; rare and costly",
  },
  {
    name: "Humanin",
    category: "Longevity & Anti-Aging",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "10 mg",
    frequency: "1–2×/week",
    cycle: "4–6 weeks",
    note: "Cell protective mitochondrial peptide",
  },
  {
    name: "MOTS-c",
    category: "Longevity & Anti-Aging",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "500 mcg – 5 mg",
    frequency: "2×/week",
    cycle: "4 weeks",
    note: "Metabolic regulator, mimics exercise",
  },
  {
    name: "NAD+",
    category: "Longevity & Anti-Aging",
    vialSize: "500–1000 mg",
    reconstitute: "4–6 mL",
    dose: "50–100 mg",
    frequency: "2–3 days/week",
    cycle: "Ongoing",
    note: "Cell energy coenzyme",
  },
  {
    name: "SS-31",
    category: "Longevity & Anti-Aging",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "500 mcg – 5 mg",
    frequency: "Daily",
    cycle: "4–8 weeks",
    note: "Mitochondrial support",
  },
  {
    name: "Vesugen",
    category: "Longevity & Anti-Aging",
    vialSize: "20 mg",
    reconstitute: "3 mL",
    dose: "1–5 mg",
    frequency: "Daily",
    cycle: "4 weeks",
    note: "Supports vascular health",
  },
  {
    name: "GHK-Cu",
    category: "Longevity & Anti-Aging",
    vialSize: "50–100 mg",
    reconstitute: "3–4 mL",
    dose: "2 mg",
    frequency: "5 days on / 2 days off",
    cycle: "6–8 weeks",
    note: "Enhances skin regeneration",
  },
  {
    name: "DSIP",
    category: "Longevity & Anti-Aging",
    vialSize: "5 mg",
    reconstitute: "2 mL",
    dose: "100–300 mcg",
    frequency: "Nightly",
    cycle: "4–8 weeks",
    note: "Enhances deep sleep",
  },
  {
    name: "NMN",
    category: "Longevity & Anti-Aging",
    vialSize: "Capsules",
    reconstitute: "N/A",
    dose: "500–1000 mg",
    frequency: "Daily",
    cycle: "8 weeks",
    note: "Precursor for NAD+ and mitochondria function",
  },
  {
    name: "Epitalon Amidate",
    category: "Longevity & Anti-Aging",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "1–3 mg",
    frequency: "Daily",
    cycle: "10–20 days",
    note: "Modified Epithalon",
  },
  {
    name: "Glutathione",
    category: "Longevity & Anti-Aging",
    vialSize: "600 mg",
    reconstitute: "4 mL",
    dose: "100 mg",
    frequency: "2–3×/week",
    cycle: "8–12 weeks",
    note: "Detox, inflammation, skin",
  },
  {
    name: "Vilon",
    category: "Immune & Gut",
    vialSize: "5 mg",
    reconstitute: "3 mL",
    dose: "5 mg",
    frequency: "Daily",
    cycle: "10–20 days",
    note: "Mild immunomodulator (subQ)",
  },
  {
    name: "VIP",
    category: "Immune & Gut",
    vialSize: "5 mg",
    reconstitute: "3 mL",
    dose: "50–100 mcg",
    frequency: "Daily",
    cycle: "2–3 months",
    note: "Regulates inflammation",
  },
  {
    name: "KPV",
    category: "Immune & Gut",
    vialSize: "10 mg",
    reconstitute: "2 mL",
    dose: "200–500 mcg",
    frequency: "5 days on / 2 days off",
    cycle: "8 weeks",
    note: "Anti-inflammatory, gut repair (subQ)",
  },
  {
    name: "LL-37",
    category: "Immune & Gut",
    vialSize: "5 mg",
    reconstitute: "2 mL",
    dose: "100 mcg",
    frequency: "Daily",
    cycle: "4–6 weeks",
    note: "Antimicrobial and healing peptide (subQ)",
  },
  {
    name: "Thymalin",
    category: "Immune & Gut",
    vialSize: "20 mg",
    reconstitute: "2 mL",
    dose: "10 mg",
    frequency: "Daily",
    cycle: "5–10 days",
    note: "Restores immune balance (subQ)",
  },
  {
    name: "Thymosin Alpha-1",
    category: "Immune & Gut",
    vialSize: "10 mg",
    reconstitute: "2 mL",
    dose: "1.5 mg",
    frequency: "2×/week",
    cycle: "6–12 weeks",
    note: "Boosts T-cell response (subQ)",
  },
  {
    name: "Kisspeptin",
    category: "Sexual Health",
    vialSize: "5 mg",
    reconstitute: "3 mL",
    dose: "100 mcg",
    frequency: "Daily",
    cycle: "4 weeks on / 4 weeks off",
    note: "Boosts GnRH and fertility",
  },
  {
    name: "Oxytocin",
    category: "Sexual Health",
    vialSize: "10 mg",
    reconstitute: "2 mL",
    dose: "20–50 mcg",
    frequency: "As needed",
    cycle: "As needed",
    note: "Enhances bonding/intimacy",
  },
  {
    name: "PT-141",
    category: "Sexual Health",
    vialSize: "10 mg",
    reconstitute: "3 mL",
    dose: "500–1000 mcg",
    frequency: "As needed",
    cycle: "As needed",
    note: "Boosts libido via MC-4R",
  },
  {
    name: "Melanotan I",
    category: "Skin & UV Protection",
    vialSize: "10 mg",
    reconstitute: "2 mL",
    dose: "250–500 mcg",
    frequency: "Daily (initial)",
    cycle: "2–4 weeks",
    note: "Induces tanning, UV protection",
  },
];
